version: '2'

networks:
    site1:
      external:
        name: site1_default
    site2:
      external:
        name: site2_default
        
services:
  proxy:
    build: ./
    networks:
      - site1
      - site2
    ports:
      - 80:80
      - 443:443